sudo: false
language: node_js
node_js:
  - 4
  - 6
  - 8
script:
  - npm test
after_success:
  - npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    # d2l-travis-deploy: a89e......2259
    secure: HtTG4VL8j5dXcI3nkeMOnjjBMhf/vIQjyAEACFIxsp/+oGm0qK/bfeBO0vAxCSYI+p/7ZqzQPK3zWPxj0HnZv0iayifvA14/O18zWJpvt2JXaRdKLkXP6jPC1GPeDkm+lzCSXIp4aTjHwIpCTtJPh0fuR5wJZnMTGP5/aj5EJZ+WoIkWSuHpoGpoX5XTatZvl1OZNvyO8kMSiJXMAjHAsI7aClBKpY0LCZ3miDg56hA7P8KPwu1diZ3hIGDpY3IssCpiq/HQL2unvzdLuRKr/GkVbw4drEneyB1tnsU7c5JYbE+hyExuY/oKOImfeucrqYQsEMmR772cWF1eP2K8xGeGKaH/33N2W81RcsL6LvZPfM6DN9eF1jQge9y020+kgI/+y/q5ymISN0VMCPyrkUvVd1NkXQYyKKrZYXVLu/TF3xb2Dmvg60TKCPoINyggaaPaFzpWhevHhVwF1qBWVZbgXWHxh1UPgSTwdDtWla5UScK7nndJhrK8dhewxi6bxFEffs2DkUMIOXVcC5WFdNn2QJ+SaXFfXI66dsudy+GLacss7iRkMwfWKsp39gK6sBGuJDCRSJwL5GnPO1kRUOeUDAITtHamkxEKyPYE3NN1XctfA9/35r/1HWa4Ooiq8xdVerAXZEg6iDvgE2/K0Ju+cwp2f9tljlAPwX+x9fI=
  on:
    tags: true
    repo: Brightspace/node-promised-method
    node: 8
