sudo: false
language: node_js
node_js:
- 4
- 6
- 8
script:
- npm test
after_success:
- npm run report-cov
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: QBj/XC7lHHMMiDvcTZEz36fCvfcf87xQXF/eLB4GQ3KqYYfsmdb0/rfMLRp/u9FAf9tz/5RyhG6t+u+CHJFuSG7u2vmztJ6mQgSQFAQPx0PiNR004syaJ71/y/D3kM26WDg4LqWt7fejec9fpzuTxrQ8H/C67i5Loe1IsDcPvNUhGKp985JDdrGc9hcFmpYW9wenl4qWCt6V3lK/KJuybg+souyfgc/tEGnWloHvZgZC0JZ+xbgT2n2a9wGHuzhwHKB65P+sEq0uwB+5UAtPaHwq8rWnqPcxd3I9gBIHg05sxuie1Pz4h4xU2/y2syM64WKQalUL4rHVHVuV8vS5bYQ6g+PasKb9bq1UIVE9VX+zdvfDQGFiIfBcrQmLTopIrskVLDwZ2o+iToMHsFJPj3LsxQtonF06ftMzc5FJFj0yk1Hg0UKh+44GvlXPTDHa8yFf4nF9DhsftG72z4zwX1ns0FptzaiHKqchG9W2zoeE2tJDtmXHEgo0obOdBSH4uxhK9x4sHDH6nyNrsDRgWvABIU5P6hi+EZ/XBz6IxcVAlkJ3B4smzAvZdncZ2r4T7myrge4bzwJJ0Tl5QISJ/TwF4r+Efl/83ZOUNKzUAvgBEJgMqXXm+vUw0ZDsDIScwKnhhqFW4QLwCnZyMUYAF42DaD9rkf0lO/CqB0179Z4=
  on:
    tags: true
    repo: Brightspace/node-promised-method
    node: 8
